# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='libromodelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('autor', models.CharField(max_length=40)),
                ('editorial', models.CharField(max_length=40)),
                ('ISBN', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9999)),
            ],
        ),
    ]
